Repository alteryx/evalml, pull requests merged in 2020-10, with the labels that each got.

#1269 Changed copyright date
  docs/source/conf.py
  docs/source/release_notes.rst
Labels: documentation

#1310 Updates to contributing.md after working with Raymond to set up dev env
  contributing.md
  docs/source/install.ipynb
  docs/source/release_notes.rst
Labels: documentation

#1334 Add codecov yaml, round coverage up instead of down
  .github/.codecov.yml
  docs/source/release_notes.rst
Labels: testing

#1335 Include editable installs in all install make targets
  .circleci/config.yml
  Makefile
  contributing.md
  docs/source/release_notes.rst
Labels: enhancement

#1356 Add DockerHub credentials to CI testing environment
  .circleci/config.yml
  docs/source/release_notes.rst
Labels: task, testing

#1370 Release v0.15.0
  docs/source/release_notes.rst
  evalml/__init__.py
  setup.py
Labels: task
