Repository alteryx/evalml, pull requests merged in 2020-11, with the labels that each got.

#1402 Update contributing guide for CLA
  contributing.md
  docs/source/release_notes.rst
Labels: documentation

#1413 Try rounding codecov down instead of up
  .github/.codecov.yml
  docs/source/release_notes.rst
Labels: testing

#1417 Update docstrings from `np.array` to `np.ndarray`
  docs/source/release_notes.rst
  docs/source/user_guide/components.ipynb
  evalml/data_checks/class_imbalance_data_check.py
  evalml/data_checks/high_variance_cv_data_check.py
  evalml/data_checks/highly_null_data_check.py
  evalml/data_checks/invalid_targets_data_check.py
  evalml/model_understanding/graphs.py
  evalml/objectives/objective_base.py
  evalml/pipelines/binary_classification_pipeline.py
  evalml/pipelines/classification_pipeline.py
  evalml/pipelines/components/component_base.py
  evalml/pipelines/components/ensemble/stacked_ensemble_base.py
  evalml/pipelines/components/estimators/classifiers/baseline_classifier.py
  evalml/pipelines/components/estimators/regressors/baseline_regressor.py
  evalml/pipelines/components/transformers/encoders/onehot_encoder.py
  evalml/pipelines/components/transformers/imputers/imputer.py
  evalml/pipelines/components/transformers/imputers/simple_imputer.py
  evalml/pipelines/components/transformers/preprocessing/text_featurizer.py
  evalml/pipelines/components/utils.py
  evalml/pipelines/pipeline_base.py
  evalml/pipelines/regression_pipeline.py
  evalml/preprocessing/utils.py
Labels: documentation

#1412 Update documentation to include all data checks and usage of data checks in AutoML
  docs/source/release_notes.rst
  docs/source/user_guide/automl.ipynb
  docs/source/user_guide/data_checks.ipynb
  evalml/data_checks/class_imbalance_data_check.py
  evalml/data_checks/default_data_checks.py
  evalml/data_checks/high_variance_cv_data_check.py
Labels: documentation

#1452 Update automl to use default of max_batches=1
  docs/source/demos/fraud.ipynb
  docs/source/demos/lead_scoring.ipynb
  docs/source/demos/text_input.ipynb
  docs/source/release_notes.rst
  docs/source/start.ipynb
  docs/source/user_guide/automl.ipynb
  evalml/automl/automl_search.py
  evalml/tests/automl_tests/test_automl.py
  evalml/tests/automl_tests/test_automl_search_classification.py
Labels: enhancement
