Repository alteryx/evalml, pull requests merged in 2020-12, with the labels that each got.

#1480 Update allow list for deps update bot
  .circleci/config.yml
  .github/workflows/dependency_check.yml
  Makefile
  docs/source/release_notes.rst
  evalml/tests/dependency_update_check/latest_dependency_versions.txt
  evalml/tests/dependency_update_check/make_deps_diff.sh
  evalml/tests/latest_dependency_versions.txt
Labels: enhancement

#1484 Pin woodwork version
  core-requirements.txt
  docs/source/release_notes.rst
Labels: enhancement

#1489 Have circleci badge filtered to main branch, not latest build
  README.md
  docs/source/release_notes.rst
Labels: enhancement

#1487 Add script to generate github markdown for release notes
  docs/source/release_notes.rst
  release.md
  tools/format_release_notes.sh
Labels: enhancement

#1494 Fix custom index bug in get_prediction_vs_actual_over_time_data
  docs/source/release_notes.rst
  evalml/model_understanding/graphs.py
  evalml/tests/model_understanding_tests/test_graphs.py
Labels: bug

#1532 Set max value for plotly and xgboost versions
  docs/source/release_notes.rst
  requirements.txt
Labels: bug

#1528 Classification Pipelines for Time Series
  docs/source/api_reference.rst
  docs/source/release_notes.rst
  evalml/objectives/binary_classification_objective.py
  evalml/objectives/multiclass_classification_objective.py
  evalml/pipelines/__init__.py
  evalml/pipelines/classification_pipeline.py
  evalml/pipelines/components/ensemble/stacked_ensemble_classifier.py
  evalml/pipelines/components/estimators/classifiers/catboost_classifier.py
  evalml/pipelines/components/estimators/classifiers/decision_tree_classifier.py
  evalml/pipelines/components/estimators/classifiers/elasticnet_classifier.py
  evalml/pipelines/components/estimators/classifiers/et_classifier.py
  evalml/pipelines/components/estimators/classifiers/lightgbm_classifier.py
  evalml/pipelines/components/estimators/classifiers/logistic_regression.py
  evalml/pipelines/components/estimators/classifiers/rf_classifier.py
  evalml/pipelines/components/estimators/classifiers/xgboost_classifier.py
  evalml/pipelines/components/utils.py
  evalml/pipelines/pipeline_base_meta.py
  evalml/pipelines/time_series_classification_pipelines.py
  evalml/pipelines/utils.py
  evalml/problem_types/problem_types.py
  evalml/tests/component_tests/test_components.py
  evalml/tests/component_tests/test_decision_tree_classifier.py
  evalml/tests/component_tests/test_en_classifier.py
  evalml/tests/component_tests/test_et_classifier.py
  evalml/tests/component_tests/test_lgbm_classifier.py
  evalml/tests/component_tests/test_stacked_ensemble_classifier.py
  evalml/tests/component_tests/test_utils.py
  evalml/tests/conftest.py
  evalml/tests/pipeline_tests/test_time_series_pipeline.py
  evalml/tests/problem_type_tests/test_problem_types.py
  evalml/tests/utils_tests/test_gen_utils.py
  evalml/utils/__init__.py
  evalml/utils/gen_utils.py
Labels: new feature

#1594 Pin sklearn version
  core-requirements.txt
  docs/source/release_notes.rst
Labels: task

#1597 AutoMLSearch: hold reference to training data
  README.md
  docs/source/demos/cost_benefit_matrix.ipynb
  docs/source/demos/fraud.ipynb
  docs/source/demos/lead_scoring.ipynb
  docs/source/demos/text_input.ipynb
  docs/source/release_notes.rst
  docs/source/start.ipynb
  docs/source/user_guide/automl.ipynb
  docs/source/user_guide/model_understanding.ipynb
  evalml/automl/__init__.py
  evalml/automl/automl_search.py
  evalml/automl/utils.py
  evalml/preprocessing/__init__.py
  evalml/preprocessing/data_splitters/__init__.py
  evalml/preprocessing/data_splitters/time_series_split.py
  evalml/preprocessing/data_splitters/training_validation_split.py
  evalml/preprocessing/utils.py
  evalml/problem_types/__init__.py
  evalml/problem_types/utils.py
  evalml/tests/automl_tests/test_automl.py
  evalml/tests/automl_tests/test_automl_search_classification.py
  evalml/tests/automl_tests/test_automl_search_regression.py
  evalml/tests/automl_tests/test_automl_utils.py
  evalml/tests/automl_tests/test_time_series_split.py
  evalml/tests/component_tests/test_target_encoder.py
  evalml/tests/objective_tests/test_cost_benefit_matrix.py
  evalml/tests/objective_tests/test_fraud_detection.py
  evalml/tests/objective_tests/test_lead_scoring.py
  evalml/tests/preprocessing_tests/test_split_data.py
  evalml/tests/preprocessing_tests/test_training_validation_split.py
  evalml/tests/problem_type_tests/test_problem_types.py
Labels: enhancement

#1569 AutoMLSearch: rename "data_split" to "data_splitter"
  docs/source/release_notes.rst
  evalml/automl/automl_search.py
  evalml/automl/utils.py
  evalml/tests/automl_tests/test_automl.py
  evalml/tests/automl_tests/test_automl_search_classification.py
Labels: refactor

#1623 Release v0.17.0
  docs/source/release_notes.rst
  evalml/__init__.py
  setup.py
Labels: task
