Repository alteryx/evalml, pull requests merged in 2021-05, with the labels that each got.

#2152 Add top-level search method
  docs/source/api_reference.rst
  docs/source/release_notes.rst
  docs/source/start.ipynb
  docs/source/user_guide/automl.ipynb
  evalml/__init__.py
  evalml/automl/__init__.py
  evalml/automl/automl_search.py
  evalml/tests/automl_tests/test_search.py
Labels: new feature

#2225 PR comment from automl first batch sort order: add test
  docs/source/release_notes.rst
  evalml/tests/automl_tests/test_iterative_algorithm.py
Labels: enhancement, testing

#2272 PipelineBase.compute_estimator_features fails for Undersampler
  docs/source/release_notes.rst
  evalml/pipelines/components/transformers/samplers/base_sampler.py
  evalml/tests/component_tests/test_components.py
  evalml/tests/component_tests/test_oversamplers.py
  evalml/tests/component_tests/test_undersampler.py
  evalml/tests/model_understanding_tests/test_permutation_importance.py
Labels: blocker, bug

#2238 Use codecov action to upload coverage reports
  .github/workflows/linux_unit_tests.yml
  docs/source/release_notes.rst
Labels: refactor, testing

#2261 Docs build: refactor markupsafe dependency pin to be outside of requirements.txt
  .readthedocs.yaml
  docs-requirements.txt
  docs/source/release_notes.rst
  evalml/tests/dependency_update_check/latest_dependency_versions.txt
  evalml/tests/dependency_update_check/minimum_requirements.txt
  requirements.txt
Labels: documentation, task, testing

#2286 Add Model Understanding Tests
  docs/source/release_notes.rst
  evalml/tests/model_understanding_tests/prediction_explanations_tests/test_explainers.py
  evalml/tests/model_understanding_tests/test_permutation_importance.py
Labels: task, testing
