Repository alteryx/evalml, pull requests merged in 2021-01, with the labels that each got.

#1566 Adding time series support to make_pipeline
  docs/source/release_notes.rst
  evalml/pipelines/utils.py
  evalml/tests/automl_tests/test_automl.py
  evalml/tests/pipeline_tests/test_pipelines.py
Labels: enhancement

#1575 Fix Automl custom objective stack trace
  docs/source/release_notes.rst
  evalml/automl/automl_search.py
  evalml/tests/automl_tests/test_automl.py
  evalml/tests/objective_tests/test_objectives.py
Labels: bug

#1641 Adding custom index support for MAPE
  docs/source/release_notes.rst
  evalml/objectives/standard_metrics.py
  evalml/tests/objective_tests/test_standard_metrics.py
Labels: bug

#1645 Pass pipeline params to time series regression baseline estimator
  docs/source/release_notes.rst
  evalml/automl/automl_search.py
  evalml/tests/automl_tests/test_automl.py
Labels: bug

#1656 Docs update for Mac graphviz
  docs/source/install.ipynb
  docs/source/release_notes.rst
Labels: documentation, enhancement

#1661 Adding positive_only objectives to non_core_objectives
  docs/source/release_notes.rst
  evalml/objectives/utils.py
  evalml/tests/automl_tests/test_automl.py
  evalml/tests/objective_tests/test_objectives.py
Labels: bug

#1691 DelayedFeatureTransformer encodes categorical features and targets
  docs/source/release_notes.rst
  evalml/pipelines/components/transformers/preprocessing/time_series.py
  evalml/pipelines/time_series_classification_pipelines.py
  evalml/tests/component_tests/test_delayed_features_transformer.py
  evalml/tests/pipeline_tests/test_time_series_baseline_pipeline.py
  evalml/tests/pipeline_tests/test_time_series_pipeline.py
Labels: enhancement

#1583 Component iteration in pipelines
  docs/source/release_notes.rst
  docs/source/user_guide/pipelines.ipynb
  evalml/pipelines/component_graph.py
  evalml/pipelines/pipeline_base.py
  evalml/pipelines/utils.py
  evalml/tests/pipeline_tests/test_pipelines.py
Labels: refactor

#1704 Add prophet regressor
  .circleci/config.yml
  docs/source/api_reference.rst
  docs/source/release_notes.rst
  evalml/model_family/model_family.py
  evalml/pipelines/components/__init__.py
  evalml/pipelines/components/estimators/__init__.py
  evalml/pipelines/components/estimators/regressors/__init__.py
  evalml/pipelines/components/estimators/regressors/prophet_regressor.py
  evalml/tests/component_tests/test_components.py
  evalml/tests/component_tests/test_prophet_regressor.py
  evalml/tests/component_tests/test_utils.py
  evalml/tests/dependency_update_check/latest_dependency_versions.txt
  evalml/tests/model_family_tests/test_model_family.py
  evalml/utils/__init__.py
  evalml/utils/gen_utils.py
  requirements.txt
Labels: new feature
