Repository alteryx/evalml, pull requests merged in 2021-02, with the labels that each got.

#1781 1434 prediction explanations dataframe output
  docs/source/release_notes.rst
  docs/source/user_guide/model_understanding.ipynb
  evalml/model_understanding/prediction_explanations/_report_creator_factory.py
  evalml/model_understanding/prediction_explanations/_user_interface.py
  evalml/model_understanding/prediction_explanations/explainers.py
  evalml/tests/model_understanding_tests/prediction_explanations_tests/test_explainers.py
Labels: enhancement

#1787 Update release doc to reflect tweak in release process
  docs/source/release_notes.rst
  release.md
Labels: documentation

#1762 Speed up permutation importance
  docs/source/release_notes.rst
  evalml/model_understanding/graphs.py
  evalml/pipelines/component_graph.py
  evalml/pipelines/components/transformers/encoders/onehot_encoder.py
  evalml/pipelines/components/transformers/encoders/target_encoder.py
  evalml/pipelines/components/transformers/preprocessing/datetime_featurizer.py
  evalml/pipelines/components/transformers/preprocessing/lsa.py
  evalml/pipelines/components/transformers/preprocessing/text_featurizer.py
  evalml/pipelines/components/transformers/transformer.py
  evalml/pipelines/pipeline_base.py
  evalml/tests/model_understanding_tests/test_graphs.py
  evalml/tests/model_understanding_tests/test_permutation_importance.py
Labels: enhancement, performance

#1800 Update README.md
  README.md
  docs/source/release_notes.rst
Labels: documentation

#1785 Data Health: Uniqueness
  docs/source/release_notes.rst
  docs/source/user_guide/data_checks.ipynb
  evalml/data_checks/__init__.py
  evalml/data_checks/data_check_message_code.py
  evalml/data_checks/uniqueness_data_check.py
  evalml/tests/data_checks_tests/test_uniqueness_data_check.py
Labels: enhancement, new feature

#1809 Updating percent better than baseline computation
  docs/source/release_notes.rst
  evalml/objectives/cost_benefit_matrix.py
  evalml/objectives/fraud_cost.py
  evalml/objectives/lead_scoring.py
  evalml/objectives/objective_base.py
  evalml/objectives/standard_metrics.py
  evalml/tests/automl_tests/test_automl.py
  evalml/tests/objective_tests/test_standard_metrics.py
Labels: enhancement

#1836 Transformers and estimators preserve custom index
  docs/source/release_notes.rst
  evalml/pipelines/components/transformers/encoders/target_encoder.py
  evalml/tests/component_tests/test_components.py
  evalml/tests/component_tests/test_target_encoder.py
Labels: enhancement

#1847 Max cap conda graphviz version
  .circleci/config.yml
  docs/source/release_notes.rst
Labels: blocker, testing

#1843 Prediction Explanations Refactor: only compute features once
  docs/source/release_notes.rst
  evalml/model_understanding/prediction_explanations/_report_creator_factory.py
  evalml/model_understanding/prediction_explanations/_user_interface.py
  evalml/model_understanding/prediction_explanations/explainers.py
  evalml/tests/model_understanding_tests/prediction_explanations_tests/test_explainers.py
Labels: performance, refactor
